# monitoring/prometheus.yml
global:
  scrape_interval: 15s # Le dice a Prometheus que recolecte métricas cada 15 segundos

scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['app:5000']